### ISSUE TITLE
Does not work in Nuxt.js (Vue SSR)

### ISSUE THREAD

**Issue by IlyaSemenov** [websmurf/vue2-notify#7]
The library won't work in Nuxt.js. Simply importing `vue2-notify` crashes with "window not defined" (coming from hard-wired `velocity-animate` dependency).

Steps to reproduce:

```
$ node                                                                                                                                 
> require('vue2-notify')
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/semenov/tmp/vue/node_modules/velocity-animate/velocity.js:417:4)
    at Module._compile (module.js:573:30)
```

**Comment by core01** [comment]
@websmurf If I try to replace velocity-animate with CSS animation and setTimeout function, what do you think about that? I'm also not thrilled about hard-wired velocity-animate dependency.

For fadeIn & fadeOut I can use this code https://vuejs.org/v2/guide/transitions.html#Transitioning-Single-Elements-Components

**Comment by websmurf** [comment]
@core01 sorry for taking this long to respond, but yes, that would be welcome
